version: 1

project_name: quip-mcp

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: quip-mcp
    binary: quip-mcp
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    builds:
      - quip-mcp
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "Merge pull request"
      - "Merge branch"

release:
  github:
    owner: bug-breeder
    name: quip-mcp
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## Quip MCP Server {{ .Tag }}
    
    A Model Context Protocol (MCP) server for Quip integration.
    
    ### Installation
    
    #### Quick Install (macOS/Linux)
    ```bash
    curl -sSL https://raw.githubusercontent.com/bug-breeder/quip-mcp/main/install.sh | bash
    ```
    
    #### Manual Download
    Download the appropriate binary for your platform from the assets below.
    
  footer: |
    ### Configuration
    
    1. Get your API token from your Quip instance
    2. Run: `quip-mcp --setup`
    3. Add to your MCP client configuration
    
    For more details, see the [README](https://github.com/bug-breeder/quip-mcp).

  extra_files:
    - glob: ./install.sh 